### ISSUE TITLE
Make user facing text display nicely

### ISSUE THREAD

**Issue by ericmtsai** [ElectionDataAnalysis/electiondata#124]
Currently the `display_options()` function will pull some information directly from the DB to display to the user. Some of this looks nice and some doesn't. It would be better to use Proper Casing for display.

Since the selection by the user (in the front end) is then passed back to make various function calls, we'll need to update the code to accommodate text that has been Proper Cased to match back to various casing in the DB.

**Comment by sfsinger19103** [comment]
Done
