### ISSUE TITLE
Importing information from MIT file has discrepancies with actual results (2018 General)

### ISSUE THREAD

**Issue by toddgraham121** [ElectionDataAnalysis/electiondata#700]
In the `[wrong_by_at_least_0.05.xlsx](https://github.com/ElectionDataAnalysis/electiondata/files/6958112/wrong_by_at_least_0.05.xlsx)` file, one of the column headers is `Database_Count` which corresponds to our internal database while the values that I acquired to test against are under the `Reference_Count` header.

The `Reference_Count` values for Minnesota were acquired using [MN’s SOS site](https://electionresults.sos.state.mn.us/results/Index?ErsElectionId=115&scenario=StateFedCounty&CountyId=11&show=Go). The `Reference_Count` for both MN;Cass and MN;Stearns were calculated by summing the number of votes under the `US Senator` race.

The discrepancy between the `Reference_Count` and `Database_Count` (14024 vs 28009 for Cass County) is due to not including the `US Senator Special Election` results in the sum. By including the votes from both the `US Senator` and `US Senator Special Election` the sum of the total votes is 28014 which is still 5 off of the `Database_Count`. There was 1 Write-in vote for the `US Senator` race and 4 Write-in votes for the `US Senator Special Election` race. By subtracting those off, we would have 28009 votes which matches the `Database_Count` column.

**Comment by sfsinger19103** [comment]
These errors are all internal to the MIT file (county2018.csv)
